---
title: "PM-592 Final Project"
author: "Jaxon Abercrombie"
date: "12/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load in Libraries and/or Sources
library(tidyverse)
library(dplyr)
library(psych)
library(knitr)
library(kableExtra)
library(mfp)
library(stargazer)
library(sjPlot)
library(glmulti)
library(LogisticDx)
```

# Functions

```{r functions, warnings = FALSE}
lrt.func <- function(model){
  model %>%
    anova(test = "LRT")
}

fp.func <- function(variable2){
  mfp(death ~ fp(variable2), data = heartfailure, family = binomial)
}

plot_resid_lev_logistic <- function(model) 
{
  resp <- names(model.frame(model))[1]
  title <- paste("Outlier and Leverage Diagnostics for", 
                 resp)
  
  g <- dx(model, byCov=T) %>% 
    rownames_to_column() %>% 
    as_tibble()
  lthresh <- round(mean(g$h, na.rm=T)*2, 3)
  ann_label <- paste("Threshold:", lthresh)
  f <- g[,c("rowname", "h", "dChisq", "dDev", "dBhat", "sPr")]
  f$numinf <- as.integer(
    (f$dChisq > 4) + (f$dDev > 4) + (f$dBhat > 1)
  )
  f$obs <- case_when(
    (f$h > lthresh) & (abs(f$sPr) > 2) ~ "Influence",
    (f$h > lthresh) ~ "Leverage",
    (abs(f$sPr) > 2) ~ "Outlier",
    TRUE ~ "Normal"
  )
  f$txt <- ifelse(f$obs == "Normal", NA, f$rowname)

    ggplot(f, aes(h, sPr, label = txt)) + 
    geom_point(shape = 1, aes(colour = obs, size = 0.5+0.25*numinf)) + 
    scale_colour_manual(values=c("Influence" = "red", "Outlier" = "maroon",
                                 "Leverage" = "darkgreen", "Normal" = "blue")) +
    labs(colour = "Observation",
         x = "Leverage",
         y = "Pearson's Residual",
         title = title) +
    geom_hline(yintercept = c(2, -2), colour = "maroon") + 
    geom_vline(xintercept = lthresh, colour = "maroon") + 
    geom_text(vjust = -1, size = 3, family = "serif", 
              fontface = "italic", colour = "darkred") + 
    annotate("text", x = Inf, y = Inf, hjust = 1.2, 
             vjust = 2, family = "serif", fontface = "italic", 
             colour = "darkred", label = ann_label) +
    scale_size(guide = "none")
  }
```

$$\\[.3in]$$

# Data Section

```{r data, warnings = FALSE}
# Load in Dataset
heartfailure <- read.csv("heartfailure.csv")

# Clean, Wrangle, and Explore Data
names(heartfailure)[13] <- "death"

names(heartfailure) # examine variable names and decide which are of interest

dim(heartfailure) # check dimensions to make sure they match source website

sum(is.na(heartfailure)) # ensure there are no cells with NA

# Summary statistics found in Table 1 in later code chunk
```

$$\\[.3in]$$

### Model Building Code and Output - Univariate

```{r univariate, warnings = FALSE}
## MAIN INDEPENDENT CONTINUOUS VARIABLES FIRST

# Creatinine Phosphokinase 
cp.m <- glm(death ~ creatinine_phosphokinase, 
            family = binomial, data = heartfailure)
summary(cp.m)
mfp(death ~ fp(creatinine_phosphokinase), 
    data = heartfailure, family = binomial)
lrt.func(cp.m)

# Ejection Fraction
ef.m <- glm(death ~ ejection_fraction, 
            family = binomial, data = heartfailure)
summary(ef.m)
mfp(death ~ fp(ejection_fraction), 
    data = heartfailure, family = binomial)
heartfailure <- 
  heartfailure %>%
  mutate(ef.fp = (1/sqrt(ejection_fraction))) # mutate based on fp output
glm(death ~ ef.fp, family = binomial, data = heartfailure) %>%
  anova(test = "LRT")
ef.m2 <- glm(death ~ ef.fp, 
            family = binomial, data = heartfailure) # new model with transformation
summary(ef.m2)

# Platelets
platelets.m <- glm(death ~ platelets, 
            family = binomial, data = heartfailure)
summary(platelets.m)
mfp(death ~ fp(platelets), 
    data = heartfailure, family = binomial)
lrt.func(platelets.m)

# Serum Creatinine
sc.m <- glm(death ~ serum_creatinine, 
            family = binomial, data = heartfailure)
summary(sc.m)
mfp(death ~ fp(serum_creatinine), 
    data = heartfailure, family = binomial)
heartfailure <- 
  heartfailure %>%
  mutate(sc.fp = (1/serum_creatinine)) # mutate based on fp output
glm(death ~ sc.fp, family = binomial, data = heartfailure) %>%
  anova(test = "LRT")
sc.m2 <- glm(death ~ sc.fp, 
            family = binomial, data = heartfailure) # new model with transformation
lrt.func(sc.m)
summary(sc.m2)


# Serum Sodium
ss.m <- glm(death ~ serum_sodium, 
            family = binomial, data = heartfailure)
summary(ss.m)
mfp(death ~ fp(serum_sodium), 
    data = heartfailure, family = binomial)
lrt.func(ss.m)



## BINOMIAL VARIABLES AFTER
# Anaemia
anaemia.m <- glm(death ~ anaemia, 
            family = binomial, data = heartfailure)
summary(anaemia.m)
lrt.func(anaemia.m)

# High Blood Pressure
hbp.m <- glm(death ~ high_blood_pressure, 
            family = binomial, data = heartfailure)
summary(hbp.m)
lrt.func(hbp.m)



## POTENTIAL CONFOUNDERS AND EFFECT MODIFIERS LAST
# Age
age.m <- glm(death ~ age, family = binomial, data = heartfailure)
summary(age.m)
mfp(death ~ fp(age), 
    data = heartfailure, family = binomial)
lrt.func(age.m)

# Sex
sex.m <- glm(death ~ sex, 
            family = binomial, data = heartfailure)
summary(sex.m)
lrt.func(sex.m)

# Diabetes
diabetes.m <- glm(death ~ diabetes, 
            family = binomial, data = heartfailure)
summary(diabetes.m)
lrt.func(diabetes.m)

# Smoking
smoke.m <- glm(death ~ smoking, 
            family = binomial, data = heartfailure)
summary(smoke.m)
lrt.func(smoke.m)
```

$$\\[.3in]$$

### Model Building and Output - Multivariate

```{r multivariate}
# Based on the univariate analyses and clinical signficance of variables, the preliminary final model begins as...

pfm1 <- glm(death ~ anaemia + creatinine_phosphokinase + ef.fp + 
              high_blood_pressure + platelets + sc.fp + serum_sodium,
            family = binomial, data = heartfailure)
summary(pfm1)

# The first preliminary final model indicates statistical significance with creat. phos., ef.fp, hbp, platelets, and sc. Before the variables that are not significant are removed, I will check to make sure potential confounders or effect modifiers do not change things...

# Adding diabetes (potential confounder)
pfm1.diabetes <- glm(death ~ anaemia + creatinine_phosphokinase + ef.fp + 
              high_blood_pressure + platelets + sc.fp + serum_sodium + diabetes,
            family = binomial, data = heartfailure)
summary(pfm1)
summary(pfm1.diabetes)



# Adding smoking (potential confounder)
pfm1.smoke <- glm(death ~ anaemia + creatinine_phosphokinase + ef.fp + 
              high_blood_pressure + platelets + sc.fp + serum_sodium + smoking,
            family = binomial, data = heartfailure)
summary(pfm1)
summary(pfm1.smoke)

# Adding age (potential effect modifier)
median(heartfailure$age)

age.young <-
  heartfailure %>%
  filter(age < 60)
  
age.older <-
  heartfailure %>%
  filter(age >= 60)

pfm1.ageY <- 
  glm(death ~ anaemia + creatinine_phosphokinase + ef.fp + 
              high_blood_pressure + platelets + sc.fp + serum_sodium + smoking,
            family = binomial, data = age.young)
summary(pfm1.ageY)

pfm1.ageO <- 
  glm(death ~ anaemia + creatinine_phosphokinase + ef.fp + 
              high_blood_pressure + platelets + sc.fp + serum_sodium + smoking,
            family = binomial, data = age.older)
summary(pfm1.ageO)

# Adding sex (potential effect modifier)
sex.male <-
  heartfailure %>%
  filter(sex == 1)
  
sex.female <-
  heartfailure %>%
  filter(sex == 0)

pfm1.sexM <- 
  glm(death ~ anaemia + creatinine_phosphokinase + ef.fp + 
              high_blood_pressure + platelets + sc.fp + serum_sodium + smoking,
            family = binomial, data = sex.male)
summary(pfm1.sexM)

pfm1.sexF <- 
  glm(death ~ anaemia + creatinine_phosphokinase + ef.fp + 
              high_blood_pressure + platelets + sc.fp + serum_sodium + smoking,
            family = binomial, data = sex.female)
summary(pfm1.sexF)
```

$$\\[.3in]$$

### Assessing Final Model

```{r final}
# Run best subset with chosen independent variables
best_subset <- glmulti(death ~ anaemia + 
          age:creatinine_phosphokinase + sex:ef.fp + 
          high_blood_pressure + platelets + 
          sc.fp + serum_sodium + age + sex, 
        data = heartfailure, level = 1, 
        family = binomial, crit="aicc", 
        confsetsize=128)

weightable(best_subset) %>% 
  head()


# Based on output of 6 best subsets, the first one will be used in final model 
# along with interactions indicated from analyzing potential effect modifiers
final.m <- 
  glm(death ~ 1 + age + anaemia + creatinine_phosphokinase + ef.fp +
        high_blood_pressure + sc.fp + sex + age:creatinine_phosphokinase +
        sex:ef.fp, data = heartfailure, family = binomial)
summary(final.m)


# Goodness of Fit, Fit Statistics, and Pseudo-R2
ResourceSelection::hoslem.test(final.m$y, fitted(final.m), g=20)
obsexp <- ResourceSelection::hoslem.test(final.m$y, fitted(final.m), g=20) %>%
  {cbind(
    .$observed,
    .$expected
  )}


DescTools::PseudoR2(final.m)


# Assumptions, Diagnostics, and Influential Observations
mfp(death ~ 1 + fp(age) + fp(anaemia) + fp(creatinine_phosphokinase) + 
      fp(ef.fp) + fp(high_blood_pressure) + fp(sc.fp) + fp(sex), 
    data = heartfailure, family = binomial)

collinearity <- DescTools::VIF(final.m)

knitr::kable(collinearity)

plot_resid_lev_logistic(final.m)
```

$$\\[.3in]$$

### Tables

```{r tables&figures}
# Table 1 - summary statistics for variables
options(scipen = 999)

sumTable <- heartfailure %>%
  select(age, anaemia, creatinine_phosphokinase, diabetes, ejection_fraction,
         high_blood_pressure, platelets, serum_creatinine, serum_sodium, sex,
         smoking, death) %>%
  psych::describe(quant = c(.1,.25,.5,.75,.90), skew = FALSE, trim = 0)

sumTable %>%
  kbl(digits = 2) %>%
  kable_classic_2(full_width = F)


# Table 2.1 - univariate analysis table
stargazer(age.m, anaemia.m, cp.m, diabetes.m, ef.m2, hbp.m,
          ci=TRUE, ci.level=0.95, 
          type = "text", align=TRUE, 
          title = "Univariate Regression Results for Outcome of Death",
          omit.stat=c("LL","f"), p.auto = TRUE)

# Table 2.2 - univariate analysis table
stargazer(platelets.m, sc.m2,ss.m, sex.m, smoke.m,
          ci=TRUE, ci.level=0.95, 
          type = "text", align=TRUE, 
          title = "Univariate Regression Results for Outcome of Death Pt II",
          omit.stat=c("LL","f"), p.auto = TRUE)


# Table 3 - final model table
stargazer(final.m,
          ci=TRUE, ci.level=0.95, 
          type = "text", align=TRUE, 
          title = "Final Model",
          omit.stat=c("LL","f"), p.auto = TRUE)

# Table 4 - Actual vs. Predicted for Final Model
obsexp %>%
  kbl(digits = 2) %>%
  kable_classic_2(full_width = F)
```
